---
# from https://github.com/Vinelab/ansible-composer/blob/master/tasks/main.yml
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: [ php, composer ]

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: [ php, composer ]

- name: make composer executable
  file: path=/usr/local/bin/composer mode=a+x state=file
  tags: [ php, composer ]
